defixiones = { 
    "2": {
		"id": "2",
		"provenance": "necropolis",
		"location": "Italia",
		"area":  "Roma",
		"image": "2-Roma.png",
		"date": "1st century BCE.",
		"date_val": [-1,-1],
		"material": ["lead"],
		"language": "Latin",
		"grouping": "erotic defixiones",
		"translation":  "Just as the dead man who is buried here can neither speak nor hold a conversation, so may Rhodine be dead, not speak to or hold a conversation with Marcus Licinius Faustus. Just as the dead man is neither with the gods nor with human beings, so may Rhodine not be with Marcus Licinius, and may she mean to him as much as this dead man who is buried here. Dis Pater, I hand Rhodine over to you, so that she may always be hated by Marcus Licinius Faustus. Also Marcus Hedius Amphio, also Gaius Popillius Apollonius, also Vennonia Hermiona, also Servia Glycinna."
 	},
	"5": {
		"id": "5",
		"provenance": "necropolis",
		"location": "Italia",
		"area": "Roma",
		"image": "5-Roma.png",
		"date": "4th century CE.",
		"date_val": [4,4],
		"material": ["lead"],
		"language": "Latin",
		"grouping": "agonistic defixiones",
		"translation": "...from this hour, from this day, from this night... trample, crush, smash and... consign to death Praeseticius the miller, son of Aselle, who lives in Regio IX, where he can be seen going about his work; and hand him over to Pluto, the King of the Dead (praeposito mortuorum), then if he snubs you, let him suffer from fevers, cold, torments, pallor, sweating, shivering morning and noon, evening and night from this hour, from this day, from this (night); and set him to so that he has no respite, but if he does manage to get better, suffocate that Praestetius [sic], in the hot bath, in the cold bath, wherever; bind him, destroy Praeseticius the son of Aselle, and if he manages to put you off by some trick or other, and mocks you, and laughs you out, overcome him, kill him again and again, the blackguard, Praeseticius the miller, son of Aselle, who lives in Regio IX, now now, quick, quick!"
	},
	"10": {
		"id": "10",
		"provenance": "unknown",
		"location": "Italia",
		"area": "Roma",
		"image": "10-Roma.png",
		"date": "75–40 BCE.",
		"date_val": [-1,-1],
		"material": ["lead"],
		"language": "Latin",
		"grouping": "agonistic defixiones",
		"translation": "Good and beautiful Proserpina or Salvia, if you prefer that I call you so, wife of Pluto, snatch away the health, the body, the complexion, the strength, and the faculties of Plotius. Hand him over to Pluto, your husband. May he not be able to escape this (curse) by his wits. Hand him over to fevers—quartan, tertian and daily—so that they wrestle and struggle with him. Let them overcome him to the point where they snatch away his soul. Thus I give over to you this victim, Proserpina or Acherusia if you prefer that I call you so. Summon for me the triple-headed hound to snatch away the heart of Plotius..."
	},
	"48": {
		"id": "48",
		"provenance": "necropolis",
		"location": "Italia",
		"area": "Roma",
		"image": "48-Roma.png",
		"date": "1st century CE.",
		"date_val": [1,1],
		"material": ["lead"],
		"language": "Latin",
		"grouping": "erotic defixiones",
		"translation": "Dis Pater, divine Proserpina, Hounds of Orcus, infernal Burners, Bonebreakers, Ghosts, Furies, Spirits of Madness, Birds of the night, Harpy birds, Ortygian birds, Virga, the Chimaera, Geryones, Sirens, Circe, the Giants, the Sphinx, he beseeches you and requests, asks you, powers of the infernal deities, you whose names are written above: that that Caecilia Prima, or whatever other name she goes under, you, Dis Pater, should send her below and assail her with terrible pangs, carry her off to your home. Divine Proserpina, may you bring it about that Caecilia Prima, or whatever other name she goes under, you send her below, take the blood from her veins, steal from that Caecilia Prima her flesh, the heat of her mind from that Caecilia Prima. Hounds of Orcus, Three-headed Creatures of Orcus, may you consume that Caecilia Prima’s liver and lungs, may you tear and rend her heart and veins, entrails, limbs, marrow, may you snatch away the eyes of Caecilia Prima and you, infernal Burners, may you burn and scorch all the other limbs of that Caecilia Prima, you, and let her not be able to live or enjoy good health, and may you carry off that Caecilia Prima to yourselves, hand over those parts of her to the infernal bone-breakers, you, let them break the bones of that Caecilia Prima, let them consume her marrow, let them tear apart her liver and lungs, and may you, infernal Bone-Breakers, deliver over that Caecilia Prima to Aurora, sister of Orcus. Aurora, sister of Orcus, may you take away sleep and slumber from that Caecilia Prima, may you inflict on her madness, pangs, stupefaction, a distressed bow (?)... up to the time when Caecilia Prima dies, perishes, wastes away; then may you, Aurora, sister of Orcinus, deliver over that Caecilia Prima to the infernal Ghosts and Furies... may you [plural] inflict upon that Cecilia Prima fear, frights, pangs.\n\nStupefaction and madness and all ...let them bring about, the same... who for herself... let her get, immoral behaviour ...that Caecilia Prima... let her always have. Immoral behaviour, that that Caecilia Prima may be oppressed, crushed by her enemies, consumed (by illness) and not... Birds of the night, Harpy birds, you, may you consume the heart of that Caecilia Prima, her hands, all her intestines, may you inflict upon all... of that Caecilia Prima anguished thoughts (?), daily, tertian and quartan fevers, until the time when you wrest away the life of that... Virga, of the infernal deities... you [singular], may you bring it about that Caecilia Prima, whom you are quite subduing, lashing, burning, scorching among those persons in the Underworld who have done all kinds of wickedness and crimes in the world above, that even so you, Virga, burn, scorch, lash, subdue that Caecilia Prima until you carry her off dead to you, just like persons upon a shore who have lost all their possessions. Himaera... may you sink your teeth into Caecilia Prima ... so that she never becomes healthy... her... may you (Caecilia Prima) swell up just like a drum, and may she die from terrible pangs until she perishes that you carry off... never... that Caecilia Prima you should scorch... let her be dead... Geryones, Sirens, Circe the dauther of the Sun, just as Minerva with her tunic alone... them, the Sirens, female monsters, detained men with their songs and Circe with her deadly drugs the companions of Ulysses... may you... that Caecilia Prima with the same evils, the same pangs you ‘help’ Caecilia, and may you her life and spirit... take away, may you deliver to the infernal... Dis Pater, divine Proserpina and Virga, he beseeches you who charges you in this matter your [plural]... shrine... her... may you bring to perfection of the perfect..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
	"51": {
		"id": "51",
		"provenance": "necropolis",
		"location": "Italia",
		"area": "Nomentum, Mentana",
		"image": "51-Nomentum.png",
		"date": "1st century BCE.",
		"date_val": [-1,-1],
		"material": ["lead"],
		"language": "Latin",
		"grouping": "erotic defixiones",
		"translation": "Malchio son/ slave of Nikon: his eyes, hands, fingers, arms, nails, hair, head, feet, thigh, belly, buttocks, navel, chest, nipples, neck, mouth, cheeks, teeth, lips, chin, eyes, forehead, eyebrows, shoulder-blades, shoulders, sinews, guts, marrow (?), belly, cock, leg, trade, income, health, I do curse in this tablet. Rufa the public slave: her hands, teeth, eyes, arms, belly, breasts, chest, bones, marrow (?), belly, guts, mouth,... feet, forehead, nails, fingers, womb, navel, cunt: these things belong to Rufa the public slave I do curse in this tablet."
        },
	"72": {
		"id": "72",
		"provenance": "necropolis",
		"location": "Italia",
		"area": "Pompeii, Pompei",
		"image": "72-Pompeii.png",
		"date": "1st–2nd centuries CE.",
		"date_val": [1, 2],
		"material": ["slate"],
		"language": "Latin",
		"grouping": "agonistic defixiones",
		"translation": "Stranger, stay a moment if it is no trouble to you, and learn what you should avoid. This man, whom I had hoped was my friend, suborned witnesses against me and initiated proceedings. I thank the gods and my own innocence; I was set free from all associated risks. Whoever of us is lying may both the Household Gods and the gods below reject him."
	},
	"96": {
		"id": "96",
		"provenance": "necropolis",
		"location": "Italia",
		"area": "Fontanaccia",
		"image": "96-Fontanaccia.png",
		"date": "2nd–3rd centuries CE.",
		"date_val": [2, 3],
		"material": ["lead"],
		"language": "Latin",
		"grouping": "agonistic defixiones",
		"translation": "Just as this letter quickly vanishes from the upper world (as?) the god Adonis, (and it) lies mute, languishes, having been dried up, in the same way may Quintus, the servant of Agrippinus, the one who is a woodland watchman, languish and become sick; and as agreed (?) may a fierce fire overcome him, at the age of forty-nine (since) he (is) not stronger than the divine powers and so (finally) he dies."
	},
	"109": {
		"id": "109",
		"provenance": "necropolis",
		"location": "Sicilia",
		"area": "Lilybaeum, Marsala",
		"image": "109-Lilybaeum.png",
		"date": "3rd century BCE",
		"date_val": [-3,-3],
		"material": ["lead"],
		"language": "Greek and Latin",
		"grouping": "juridicial defixiones",
		"translation": "I bind down Zopyrion son of Mymbyr before Persephone and before the underground Titans and before the abominating (male) dead. (And I bind him down) also before the priestesses of Demeter and before (the) abominating (sc. female dead). And I bind him down in lead, him and his mind and soul, so that he will be unable to speak in opposition. And I bind her down in lead, (i.e.) S[--]`yn, her and her mind and her soul. I bind them down so that they will be unable to speak or act against (me) [list of names follow]."
        },
	"117": {
		"id": "117",
		"provenance": "unknown",
		"location": "Italia",
		"area": "Locus incertus",
		"image": "117-LocusIncertus.png",
		"date": "4th–5th centuries CE",
		"date_val": [4, 5],
		"material": ["lead"],
		"language": "Greek and Latin",
		"grouping": "agonistic defixiones",
		"translation": "Porcellus. Porcellus the veterinarian. Porcellus the physician. The veterinarian. Destroy his entire body, his head, teeth, eyes... Let Porcellus and his wife, Maurilla, be... (?) May all Porcello’s body, limbs, entrails... disintegrate, languish and collapse. Porcellus the veterinarian and Maurilla his (wife). Porcellus. Porcellus. Veterinarian (?) Porcellus the veterinarian. Destroy, crush, kill, strangle Porcellus and his wife Maurilla. Their soul, heart, buttocks, liver...’\n(fragment II): ‘...tertian, quartan, (fevers?) ...pallor, colds, diseases ...Porcellus the veterinarian ...Fire (?) ...’" 
},
	"118": {
		"id": "118",
		"provenance": "unknown",
		"location": "Italia",
		"area": "Locus incertus",
		"image": "118-LocusIncertus.png",
		"date": "4th–5th centuries CE",
		"date_val": [4, 5],
		"material": ["lead"],
		"language": "Greek and Latin",
		"grouping": "agonistic defixiones",
		"translation": "Crush, kill Fistus the senator. Crush, kill Fistus. Crush (...) Fistus the senator... Crush, kill Fistus the senator. May Fistus dilute, languish, sink and may all his limbs dissolve, all his entrails (?) of Fistus. Dissolve his limbs and entrails (?), may he languish. Burst his veins (?), break all his limbs. Fistus the senator..."
        },
	"121": {
		"id": "121",
		"provenance": "sanctuary",
		"location": "Hispania",
		"area": "Salacia, Alcácer do Sal",
		"image": "121-Salacia.png",
		"date": "second half of the 1st century CE",
		"date_val": [1,1],
		"material": ["lead"],
		"language": "Latin",
		"grouping": "defixiones in fures",
		"translation": "Lord, great and invincible, you who have received the body of Attis, please receive the body of the one who took away my baggage, who robbed me from the house of Hispanus. His body (viz. the thief ’s) and his soul I give (you), I confer on you in order that I may find my possessions. I vow to give you a four-footed sacrificial victim, Lord Attis, if I find that thief. Lord Attis, I implore you by your Nocturnus, that you make me obtain my wish as soon as possible."
        },
	"131": {
		"id": "131",
		"provenance": "necropolis",
		"location": "Hispania",
		"area": "Celti, Peñaflor",
		"image": "131-Celti.png",
		"date": "second half of the 1st century BCE",
		"date_val": [-1,-1],
		"material": ["lead"],
		"language": "Latin",
		"grouping": "juridicial defixiones",
		"translation": "May Valerius Marcellus fall silent and unable to speak against Caius Licinius Gallus. Just as a frog without a tongue is mute and silent, so may Marcellus be mute, silent, enfeebled against Licinius Gallus."
        },
	"140": {
		"id": "140",
		"provenance": "unknown",
		"location": "Hispania",
		"area": "Saguntum, Sagunto",
		"image": "140-Saguntum.png",
		"date": "70 CE",
		"date_val": [1,1],
		"material": ["lead"],
		"language": "Latin",
		"grouping": "erotic defixiones",
		"translation": "May Quintula never be in a relationship with Fortunalis again."
	},
	"205": {
		"id": "205",
		"provenance": "sanctuary",
		"location": "Britannia",
		"area": "Lydney",
		"image": "205-Lydney.png",
		"date": "4th–5th centuries CE",
		"date_val": [4, 5],
		"material": ["lead"],
		"language": "Latin",
		"grouping": "defixiones in fures",
		"translation": "To the god Nodens: Silvianus has lost his ring and given half (its value) to Nodens. Among those who are called Senicianus, do not allow him health until he brings it to the temple of Nodens. (This curse) comes into force again."
        },
	"210": {
		"id": "210",
		"provenance": "sanctuary",
		"location": "Britannia",
		"area": "Aquae Sulis, Bath",
		"image": "210-AquaeSulis.png",
		"date": "unknown",
		"date_val": [0,0],
		"material": ["lead"],
		"language": "Latin",
		"grouping": "defixiones in fures",
		"translation": "Docimedis has lost two gloves. May (the person) who has stolen them should lose his minds [sic] and his eyes in the temple where (she) appoints."
	},
	"249": {
		"id": "249",
		"provenance": "sanctuary",
		"location": "Britannia",
		"area": "Aquae Sulis, Bath",
		"image": "249-AquaeSulis.png",
		"date": "275–400 CE",
		"date_val": [3, 4],
		"material": ["lead", "tin", "copper"],
		"language": "Latin",
		"grouping": "defixiones in fures",
		"translation": "(The person) who has lifted my bronze vessel is utterly accursed. I give (him) to the temple of Sulis, whether woman or man, whether slave or free, whether boy or girl, and let him who has done this spill his own blood into the vessel itself. I give, whether woman or man, whether slave or free, whether boy or girl, that thief who has stolen the property itself (that) the god may find (him)."
	},
    "299": {
		"id": "299",
		"provenance": "sanctuary",
		"location": "Britannia",
		"area": "Aquae Sulis, Bath",
		"image": "299-AquaeSulis.png",
		"date": "275–400 CE",
		"date_val": [3, 4],
		"material": ["lead", "tin", "copper"],
		"language": "Latin",
		"grouping": "defixiones in fures",
		"translation": "Uricalus, Docilosa his wife, Docilis his son and Docilina, Decentinus his brother, Alogiosa: the names of those who have sworn {who have sworn} at the spring of the goddess Sulis on the 12th of April. Whosoever has perjured himself there you are to make him pay for it to the goddess Sulis in his own blood."
	},
	"337": {
		"id": "337",
		"provenance": "amphitheatre",
		"location": "Britannia",
		"area": "Isca Silurum, Caerleon",
		"image": "337-IscaSilurum.png",
		"date": "1st–2nd centuries CE",
		"date_val": [1, 2],
		"material": ["lead"],
		"language": "Latin",
		"grouping": "defixiones in fures",
		"translation": "Lady Nemesis! I give you this cloak and these shoes. May the person who has taken them not buy back (them) except with his own life and blood."
	},
	"345": {
		"id": "345",
		"provenance": "necropolis",
		"location": "Britannia",
		"area": "Clothall",
		"image": "345-Clothall.png",
		"date": "unknown",
		"date_val": [0,0],
		"material": ["lead"],
		"language": "Latin",
		"grouping": "erotic defixiones",
		"translation": "Tacita, hereby accursed, is labelled old like putrid gore."
	},
	"353": {
		"id": "353",
		"provenance": "pit or well",
		"location": "Britannia",
		"area": "Old Harlow",
		"image": "353-OldHarlow.png",
		"date": "3rd–4th centuries CE",
		"date_val": [3, 4],
		"material": ["lead"],
		"language": "Latin",
		"grouping": "erotic defixiones",
		"translation": "HTo the god Mercury, I entrust to you my affair with Eterna and her own self, and may Timotneus feel no jealousy of me at the risk of his life- blood. I entrust to you, O Mercury, another transaction..."
        },
	"365": {
		"id": "365",
		"provenance": "sanctuary",
		"location": "Britannia",
		"area": "Uley",
		"image": "365-Uley.png",
		"date": "2nd–3rd centuries CE",
		"date_val": [2, 3],
		"material": ["lead"],
		"language": "Latin",
		"grouping": "defixiones in fures",
		"translation": "Honoratus to the holy god Mercury. I complain to your divinity that I have lost two wheels and four cows and many small belongings from my house. \nI would ask the genius of your divinity that you do not allow health to the person who has done me wrong, nor allow him to lie or sit or drink or eat, whether he is man or woman, whether boy or girl, whether slave or free, unless he brings my property to me and is reconciled with me. With renewed prayers I ask your divinity that my petition may be immediately fulfilled (and that it become obvious) that I have been avenged by your majesty."
	},
	"464": {
		"id": "464",
		"provenance": "necropolis",
		"location": "Germania",
		"area": "Colonia Claudia Ara Agrippinensium, Cologne",
		"image": "464-Colonia.png",
		"date": "mid-1st century CE",
		"date_val": [1,1],
		"material": ["lead"],
		"language": "Latin",
		"grouping": "agonistic defixiones",
		"translation": "Vaeraca, in this way may you undertake your affairs backwards, just as this text is written backwards. Whatever you wish for us, may come down on your head."
        },
	"472": {
		"id": "472",
		"provenance": "necropolis",
		"location": "Germania",
		"area": "Cruciniacum, Bad Kreuznach",
		"image": "472-Cruciniacum.png",
		"date": "2nd century CE",
		"date_val": [2,2],
		"material": ["lead"],
		"language": "Latin",
		"grouping": "erotic defixiones",
		"translation": "The names given, handed over, bound(?) to the Underworld, so that (the infernal gods) seize them by force. Silonia (curses) Surus, Caenus, Secundus. That (Secundus) proposes to you (Silonia). (But) I love him(, too)."
	},
	"478": {
		"id": "478",
		"provenance": "necropolis",
		"location": "Germania",
		"area": "Frankfurt am Main",
		"image": "478-Frankfurt.png",
		"date": "2nd century CE",
		"date_val": [2,2],
		"material": ["lead"],
		"language": "Latin",
		"grouping": "juridicial defixiones",
		"translation": "I ask [you], Manes of the underworld, may Marius Fronto, the enemy of Sextus, be untrustworthy, may he be unable to speak against Sextus, may he become mute when he approaches the legate, may he be mute and unable to speak or do anything as if he were nobody in the underworld."
	},
	"483": {
		"id": "483",
		"provenance": "unknown",
		"location": "Germania",
		"area": "Groß-Gerau",
		"image": "483-Groß-Gerau.png",
		"date": "1st century CE",
		"date_val": [1,1],
		"material": ["lead"],
		"language": "Latin",
		"grouping": "defixiones in fures",
		"translation": "The man who stole the little cloak of Verio or his things, who diminish them (i.e., his possessions), that his/her mind and memory be destroyed, or the woman or those who diminish the things of Verio, that in his/her hands, head, feet, the worms, the cancer, the worms penetrate, (that they) penetrate in his/her limbs and marrows."
	},
	"484": {
		"id": "484",
		"provenance": "sanctuary",
		"location": "Germania",
		"area": "Mogontiacum, Mainz",
		"image": "484-Mogontiacum.png",
		"date": "1st–first third of the 2nd century CE",
		"date_val": [1, 2],
		"material": ["lead"],
		"language": "Latin",
		"grouping": "erotic defixiones",
		"translation": "(Whatever) Aemilia Prima, (the lover?) of Narcissus may do, whatever she attempts, whatever she does, let it all go wrong. May she get up (out of bed) out of her senses/mind. Whatever she strives after, may her striving in all things be reversed. May this befall Prima, the lover of Narcissus: just as this letter never shall bloom, so she shall never bloom in any way."
	},
	"491": {
		"id": "491",
		"provenance": "sanctuary",
		"location": "Germania",
		"area": "Mogontiacum, Mainz",
		"image": "​​491-Mogontiacum.png",
		"date": "1st century–first third of the 2nd century CE",
		"date_val": [1, 2],
		"material": ["lead"],
		"language": "Latin",
		"grouping": "defixiones in fures",
		"translation": "Mater Magna, I ask you by your sanctuary and your divine force. Gemella who stole my brooches (I ask you) may she (...) so that no part of her be healthy. Just as the galli have cut themselves, so (may) she want to do. And may she not cut herself so, that she may lament herself. As they have deposited the holy things in the sanctuary, so also your life and health, Gemella. Neither by offerings nor by gold nor by silver may you be able to redeem yourself from the Mater Deum, except that the people may watch your death. — Verecunda and Paterna: for thus I give her to you, Mater Deum Magna, their property (...) I ask they may be destroyed just as they have defrauded me of my property and resources, nor may they be able to buy themselves free either by offering sheep or by lead (tablets); neither by gold nor silver may they buy themselves free from your divine power, until dogs devour them, worms and other horrible things; may the people watch their death just as... two (...) with writings (...) them, if [someone takes?] those hidden golden holy boxes... holy ones."
        },
	"492": {
		"id": "492",
		"provenance": "sanctuary",
		"location": "Germania",
		"area": "Mogontiacum, Mainz",
		"image": "492-Mogontiacum.png",
		"date": "1st century–first third of the 2nd century CE",
		"date_val": [1, 2],
		"material": ["lead"],
		"language": "Latin",
		"grouping": "defixiones in fures",
		"translation": "I entreat you, Mistress Mater Magna, to avenge me regarding the goods of Florus, my husband, of which Ulattius Severus has defrauded me. Just as I write this in a hostile way, so may everything, whatever he does, whatever he attempts, everything go awry for him. As salt (melts in) water, so may it happen to him. Whatever of the goods of Florus, my husband, he has taken away from me, I entreat you, Mistress Mater Magna, to avenge me for it."
	},
	"523": {
		"id": "523",
		"provenance": "necropolis",
		"location": "Germania",
		"area": "Veldidena, Wilten",
		"image": "523-Veldidena.png",
		"date": "1st century CE",
		"date_val": [1,1],
		"material": ["lead"],
		"language": "Latin",
		"grouping": "defixiones in fures",
		"translation": "Secundina commands of Mercurius and Moltinus, concerning however has stolen two steers or fourteen denarii, that deceitful Cacus remove him and his fortune, just as hers were taken, the very things which she hands over to you so that you will track them down and separate him from his fortune, from his family and from his dear ones. She commands you on this, you must bring them to justice."
	},
	"526": {
		"id": "526",
		"provenance": "necropolis",
		"location": "Noricum",
		"area": "Faviana, Mautern",
		"image": "526-Faviana.png",
		"date": "3rd century CE",
		"date_val": [3,3],
		"material": ["lead"],
		"language": "Latin",
		"grouping": "defixiones in fures",
		"translation": "Pluto, or perhaps I should say Jupiter of the Underworld, Aeracura, Juno of the Underworld, summon now quickly the one inscribed below and hand him over to the Manes. The Caesarian Aurelius Sinnianus. Thus, Silvia, you see your husband upside-down, just as his name is written."
	},
	"530": {
		"id": "530",
		"provenance": "amphitheatre",
		"location": "Pannonia",
		"area": "Carnuntum, Petronell",
		"image": "530-Carnuntum.png",
		"date": "end of 2nd century–beginning of the 3rd century CE",
		"date_val": [2, 3],
		"material": ["lead"],
		"language": "Greek and Latin",
		"grouping": "defixiones in fures",
		"translation": "Holy Dis Pater, and Veracura and assisting Cerberus, you who guard the infernal and celestial thresholds (magic signs, together with a reference to the amulet of the seal of Solomon). I request you to send Eudemus into the underworld as quickly as possible. May he return the vessel before nine days come. I curse Eudemus, slay him to a hurtful death, lead him to the underworld, with his hands bound behind him, you attendants of the infernal gods. Just like this lead has its weight so Eudemus (may?) find you angry. (Hand him) as a victim among the ghosts, as quickly as possible."
	}
}